import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:goldfish/core/data/models/visit_model.dart';
import 'package:goldfish/core/data/visit_exceptions.dart';

/// Result of a visit repository operation.
///
/// Contains the event name for logging purposes, the visit ID, user ID, and
/// optionally the visit model (for retrieval operations).
class VisitResult {
  /// Creates a new [VisitResult].
  const VisitResult({
    required this.eventName,
    required this.visitId,
    required this.userId,
    this.visit,
  });

  /// The event name for logging (e.g., 'visit_create', 'visit_get',
  /// 'visit_get_not_found').
  final String eventName;

  /// The visit ID involved in the operation.
  final String visitId;

  /// The user ID involved in the operation.
  final String userId;

  /// The visit model, if available (typically only for retrieval operations).
  final Visit? visit;

  /// Whether the operation succeeded.
  ///
  /// For retrieval operations, this is `true` if the visit was found.
  /// For create operations, this is always `true` (they throw on failure).
  bool get succeeded =>
      visit != null ||
      (eventName != 'visit_get_not_found' &&
          eventName != 'visit_get_ownership_mismatch');
}

/// Repository for managing visit data in Firestore.
///
/// Handles creating, reading, and querying visit documents in the cloud.
class VisitRepository {
  /// Creates a new [VisitRepository].
  ///
  /// The [firestore] parameter can be a real [FirebaseFirestore] instance or
  /// a compatible fake such as `FakeFirebaseFirestore` for tests, following
  /// the Firebase testing guidance at
  /// https://firebase.flutter.dev/docs/testing/testing/.
  VisitRepository({required FirebaseFirestore firestore})
    : _firestore = firestore;

  /// Underlying Firestore instance (real or fake).
  final FirebaseFirestore _firestore;

  /// Collection name for visits in Firestore.
  static const String _visitsCollection = 'visits';

  /// Creates a new visit document in Firestore.
  ///
  /// The visit's ID will be auto-generated by Firestore if not provided.
  /// Returns [VisitResult] on success.
  /// Throws [VisitDataException] if the operation fails.
  Future<VisitResult> createVisit(Visit visit) async {
    try {
      // Validate the visit before saving
      final validationErrors = visit.validate();
      if (validationErrors.isNotEmpty) {
        throw VisitDataException(
          'firestore',
          'visit_validation_error',
          visitId: visit.id,
          userId: visit.userId,
        );
      }

      // If visit has an ID, use it; otherwise let Firestore generate one
      final docRef = visit.id != null
          ? _firestore.collection(_visitsCollection).doc(visit.id)
          : _firestore.collection(_visitsCollection).doc();

      await docRef.set(visit.toMap());

      return VisitResult(
        eventName: 'visit_create',
        visitId: docRef.id,
        userId: visit.userId,
      );
    } catch (e) {
      if (e is VisitDataException) {
        rethrow;
      }

      throw VisitDataException(
        'firestore',
        'visit_create_error',
        visitId: visit.id,
        userId: visit.userId,
        innerError: e,
      );
    }
  }

  /// Gets all visits for a user, ordered by most recent first.
  ///
  /// Returns an empty list if the user has no visits.
  /// Throws [VisitDataException] if the operation fails.
  /// Individual visit parse errors are silently skipped to allow processing
  /// of other visits.
  Future<List<Visit>> getUserVisits(String userId) async {
    try {
      final querySnapshot = await _firestore
          .collection(_visitsCollection)
          .where('user_id', isEqualTo: userId)
          .orderBy('added_at', descending: true)
          .get();

      final visits = <Visit>[];
      for (final doc in querySnapshot.docs) {
        try {
          final visit = Visit.fromMap(doc.data(), doc.id);
          visits.add(visit);
        } on Exception {
          // Continue processing other visits even if one fails to parse
          // The parse error information is lost, but this allows the operation
          // to succeed for valid visits
        }
      }

      return visits;
    } catch (e) {
      if (e is VisitDataException) {
        rethrow;
      }

      throw VisitDataException(
        'firestore',
        'visit_get_user_visits_error',
        userId: userId,
        innerError: e,
      );
    }
  }

  /// Gets a single visit by ID, verifying it belongs to the specified user.
  ///
  /// Returns [VisitResult] with [VisitResult.visit] set if the visit exists
  /// and belongs to the user, or `null` if not found or ownership mismatch.
  /// Throws [VisitDataException] if the operation fails.
  Future<VisitResult> getVisitById(String id, String userId) async {
    try {
      final doc = await _firestore.collection(_visitsCollection).doc(id).get();

      if (!doc.exists) {
        return VisitResult(
          eventName: 'visit_get_not_found',
          visitId: id,
          userId: userId,
        );
      }

      final data = doc.data() as Map<String, dynamic>;
      final visitUserId = data['user_id'] as String?;

      // Verify ownership
      if (visitUserId != userId) {
        return VisitResult(
          eventName: 'visit_get_ownership_mismatch',
          visitId: id,
          userId: userId,
        );
      }

      final visit = Visit.fromMap(data, doc.id);

      return VisitResult(
        eventName: 'visit_get',
        visitId: id,
        userId: userId,
        visit: visit,
      );
    } catch (e) {
      if (e is VisitDataException) {
        rethrow;
      }

      throw VisitDataException(
        'firestore',
        'visit_get_error',
        visitId: id,
        userId: userId,
        innerError: e,
      );
    }
  }
}
