import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:goldfish/core/data/models/visit_model.dart';
import 'package:goldfish/core/data/visit_exceptions.dart';
import 'package:goldfish/core/logging/app_logger.dart';

/// Repository for managing visit data in Firestore.
///
/// Handles creating, reading, and querying visit documents in the cloud.
class VisitRepository {
  /// Creates a new [VisitRepository].
  ///
  /// The [firestore] parameter can be a real [FirebaseFirestore] instance or
  /// a compatible fake such as `FakeFirebaseFirestore` for tests, following
  /// the Firebase testing guidance at
  /// https://firebase.flutter.dev/docs/testing/testing/.
  VisitRepository({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  /// Underlying Firestore instance (real or fake).
  final FirebaseFirestore _firestore;

  /// Collection name for visits in Firestore.
  static const String _visitsCollection = 'visits';

  /// Creates a new visit document in Firestore.
  ///
  /// The visit's ID will be auto-generated by Firestore if not provided.
  /// Throws [VisitDataException] if the operation fails.
  Future<String> createVisit(Visit visit) async {
    try {
      // Validate the visit before saving
      final validationErrors = visit.validate();
      if (validationErrors.isNotEmpty) {
        throw VisitDataException(
          'Invalid visit: ${validationErrors.join(', ')}',
        );
      }

      // If visit has an ID, use it; otherwise let Firestore generate one
      final docRef = visit.id != null
          ? _firestore.collection(_visitsCollection).doc(visit.id)
          : _firestore.collection(_visitsCollection).doc();

      await docRef.set(visit.toMap());

      AppLogger.info({
        'event': 'visit_create',
        'visit_id': docRef.id,
        'user_id': visit.userId,
      });

      return docRef.id;
    } catch (e) {
      AppLogger.error({
        'event': 'visit_create',
        'user_id': visit.userId,
        'error': e.toString(),
      });

      if (e is VisitDataException) {
        rethrow;
      }

      throw VisitDataException('Failed to create visit: ${e.toString()}');
    }
  }

  /// Gets all visits for a user, ordered by most recent first.
  ///
  /// Returns an empty list if the user has no visits.
  /// Throws [VisitDataException] if the operation fails.
  Future<List<Visit>> getUserVisits(String userId) async {
    try {
      final querySnapshot = await _firestore
          .collection(_visitsCollection)
          .where('user_id', isEqualTo: userId)
          .orderBy('added_at', descending: true)
          .get();

      final visits = <Visit>[];
      for (final doc in querySnapshot.docs) {
        try {
          final visit = Visit.fromMap(
            doc.data(),
            doc.id,
          );
          visits.add(visit);
        } catch (e) {
          AppLogger.error({
            'event': 'visit_parse_error',
            'visit_id': doc.id,
            'user_id': userId,
            'error': e.toString(),
          });
          // Continue processing other visits even if one fails to parse
        }
      }

      AppLogger.info({
        'event': 'visit_get_user_visits',
        'user_id': userId,
        'count': visits.length,
      });

      return visits;
    } catch (e) {
      AppLogger.error({
        'event': 'visit_get_user_visits',
        'user_id': userId,
        'error': e.toString(),
      });
      throw VisitDataException(
        'Failed to get user visits: ${e.toString()}',
      );
    }
  }

  /// Gets a single visit by ID, verifying it belongs to the specified user.
  ///
  /// Returns `null` if the visit doesn't exist or doesn't belong to the user.
  /// Throws [VisitDataException] if the operation fails.
  Future<Visit?> getVisitById(String id, String userId) async {
    try {
      final doc = await (_firestore as dynamic)
          .collection(_visitsCollection)
          .doc(id)
          .get();

      if (!doc.exists) {
        AppLogger.info({
          'event': 'visit_get_not_found',
          'visit_id': id,
          'user_id': userId,
        });
        return null;
      }

      final data = doc.data() as Map<String, dynamic>;
      final visitUserId = data['user_id'] as String?;

      // Verify ownership
      if (visitUserId != userId) {
        AppLogger.info({
          'event': 'visit_get_ownership_mismatch',
          'visit_id': id,
          'user_id': userId,
          'visit_user_id': visitUserId,
        });
        return null;
      }

      final visit = Visit.fromMap(data, doc.id as String);

      AppLogger.info({
        'event': 'visit_get',
        'visit_id': id,
        'user_id': userId,
      });

      return visit;
    } catch (e) {
      AppLogger.error({
        'event': 'visit_get',
        'visit_id': id,
        'user_id': userId,
        'error': e.toString(),
      });
      throw VisitDataException(
        'Failed to get visit: ${e.toString()}',
      );
    }
  }
}

