# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Additional recommended rules for better code quality
    prefer_single_quotes: true
    require_trailing_commas: true
    # Ensure proper null safety usage
    avoid_null_checks_in_equality_operators: true
    # Code style and clarity
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    # Documentation
    public_member_api_docs: false  # Optional: enable if you want to enforce API docs
    # Error handling
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    # Performance
    use_build_context_synchronously: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    missing_return: error
    # Treat type errors as errors
    invalid_assignment: error
    # Treat null safety issues as errors
    invalid_null_aware_operator: error

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
